name 'awesome_customers'
maintainer 'The Authors'
maintainer_email 'ram@endpoint.com'
license 'all_rights'
description 'Installs/Configures awesome_customers'
long_description 'Installs/Configures awesome_customers'
version '0.4.0'
depends 'apt', '~> 2.6.1'
depends 'httpd', '<= 0.2.4'
depends 'firewall', '~> 0.11.8'
depends 'php', '~> 1.7.0'
depends 'mysql2_chef_gem', '~> 1.0.1'
depends 'mysql', '~> 6.0.17'
depends 'database', '~> 4.0.3'
